# Generated by Django 3.2.23 on 2024-02-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_count',
            new_name='posts_count',
        ),
    ]
