# Generated by Django 3.2.23 on 2024-03-10 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_post_count_user_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people_you_may_know',
            field=models.ManyToManyField(related_name='_account_user_people_you_may_know_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
