# Generated by Django 3.2.23 on 2024-02-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20240218_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likes_count',
        ),
    ]
