# Generated by Django 3.2.23 on 2024-03-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
