# Generated by Django 3.2.23 on 2024-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('newfollowerrequest', 'New followerrequest'), ('acceptedfollowerrequest', 'Accepted followerrequest'), ('rejectedfollowerrequest', 'Rejected followerrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment')], max_length=50),
        ),
    ]
