# Generated by Django 3.2.23 on 2024-03-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20240307_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_followerrequest', 'New followerrequest'), ('accepted_followerrequest', 'Accepted followerrequest'), ('rejected_followerrequest', 'Rejected followerrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment')], max_length=50),
        ),
    ]
